services:

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sample'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=sample'
    ports:
      - '33062:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "63792:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
