spring:
  application:
    name: sample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33062/sample
    username: sample
    password: 1234
  data:
    redis:
      port: 63792
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  docker:
    compose:
      lifecycle-management: start_only
      start:
        command: up
      stop:
        command: down
        timeout: 1m