spring:
  application:
    name: sample
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:33062/sample
    username: sample
    password: 1234
  data:
    redis:
      host: localhost
      port: 63792
      username: default
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  docker:
    compose:
      lifecycle-management: start_only # start_only, start_and_stop 옵션이 있으며, 스프링 종료 시 컨테이너 종료 여부를 결정할 수 있음
      start:
        command: up
      stop:
        command: down
        timeout: 1m

jwt:
  secret:
    key: aGVsbG9teW5hbWVpc2ppZ29vYW5kbmljZXRvbWVldHlvdXRvb2dvb2Rtb3JuaW5nc3VuYW5kbW9vbmhhdmVhbmljZWRheWhhdmVhZ29vZGRheXRvZGll

sample:
  api:
    url: http://localhost:8080/samples/properties
    key: SAMPLE_API_KEY